//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabitatHomeBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HabitatHomeBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s the {&amp;}?.
        /// </summary>
        internal static string Order_RecipientFirstName_Prompt {
            get {
                return ResourceManager.GetString("Order_RecipientFirstName_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! Your product will be delivered to {0}..
        /// </summary>
        internal static string OrderDialog_Address_Entered {
            get {
                return ResourceManager.GetString("OrderDialog_Address_Entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option you have selected is invalid.
        /// </summary>
        internal static string ProductsDialog_InvalidOption {
            get {
                return ResourceManager.GetString("ProductsDialog_InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the top {0} products Would you like to buy any?.
        /// </summary>
        internal static string ProductsDialog_Prompt {
            get {
                return ResourceManager.GetString("ProductsDialog_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string ProductsDialog_Select {
            get {
                return ResourceManager.GetString("ProductsDialog_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s your billing address? Include apartment # if needed..
        /// </summary>
        internal static string RootDialog_BillingAddress_Prompt {
            get {
                return ResourceManager.GetString("RootDialog_BillingAddress_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your billing address.
        /// </summary>
        internal static string RootDialog_BillingAddress_SelectSaved {
            get {
                return ResourceManager.GetString("RootDialog_BillingAddress_SelectSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed my mind.
        /// </summary>
        internal static string RootDialog_Checkout_Cancel {
            get {
                return ResourceManager.GetString("RootDialog_Checkout_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add credit card.
        /// </summary>
        internal static string RootDialog_Checkout_Continue {
            get {
                return ResourceManager.GetString("RootDialog_Checkout_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order with ID &apos;{0}&apos; does not exists or is not confirmed. Please try to checkout again..
        /// </summary>
        internal static string RootDialog_Checkout_Error {
            get {
                return ResourceManager.GetString("RootDialog_Checkout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you like these delivered?.
        /// </summary>
        internal static string RootDialog_DeliveryDate_Prompt {
            get {
                return ResourceManager.GetString("RootDialog_DeliveryDate_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start over.
        /// </summary>
        internal static string RootDialog_Menu_StartOver {
            get {
                return ResourceManager.GetString("RootDialog_Menu_StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have canceled the operation. What would you like to do next?.
        /// </summary>
        internal static string RootDialog_Order_Cancelation {
            get {
                return ResourceManager.GetString("RootDialog_Order_Cancelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong :(. Technical Details: {0}.
        /// </summary>
        internal static string RootDialog_Order_Error {
            get {
                return ResourceManager.GetString("RootDialog_Order_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to see top products?.
        /// </summary>
        internal static string RootDialog_OrderProduct {
            get {
                return ResourceManager.GetString("RootDialog_OrderProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        internal static string RootDialog_Receipt_OrderID {
            get {
                return ResourceManager.GetString("RootDialog_Receipt_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        internal static string RootDialog_Receipt_PaymentMethod {
            get {
                return ResourceManager.GetString("RootDialog_Receipt_PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitat Home Receipt.
        /// </summary>
        internal static string RootDialog_Receipt_Title {
            get {
                return ResourceManager.GetString("RootDialog_Receipt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support will contact you shortly. Have a nice day :).
        /// </summary>
        internal static string RootDialog_Support_Message {
            get {
                return ResourceManager.GetString("RootDialog_Support_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong after too many invalid attemps. Maybe you can start over again..
        /// </summary>
        internal static string RootDialog_TooManyAttempts {
            get {
                return ResourceManager.GetString("RootDialog_TooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a valid option. Please try again..
        /// </summary>
        internal static string RootDialog_Welcome_Error {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Habitat Home Bot. You can now order products or talk to support without leaving this bot..
        /// </summary>
        internal static string RootDialog_Welcome_Message {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order products.
        /// </summary>
        internal static string RootDialog_Welcome_Orders {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the products you are looking for!.
        /// </summary>
        internal static string RootDialog_Welcome_Subtitle {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to support.
        /// </summary>
        internal static string RootDialog_Welcome_Support {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Habitat Home Bot.
        /// </summary>
        internal static string RootDialog_Welcome_Title {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Cart.
        /// </summary>
        internal static string ShowCartDialog_MiniCart_Title {
            get {
                return ResourceManager.GetString("ShowCartDialog_MiniCart_Title", resourceCulture);
            }
        }
    }
}
